---
- name: set interfaces
  include: set_interface.yml
  vars:
    name: "{{item.key}}"
    proto: "{{item.value.proto | default('')}}"
    type: "{{item.value.type | default('')}}"
    ifname: "{{item.value.ifname | default('')}}"
    ipaddr: "{{item.value.ipaddr | default('')}}"
    netmask: "{{item.value.netmask | default('')}}"
    username: "{{item.value.username | default('')}}"
    password: "{{item.value.password | default('')}}"
    auto: "{{item.value.auto | default('')}}"
  with_dict: "{{interfaces}}"

- name: set switch_vlans
  include: set_switch_vlan.yml
  vars:
    index: "{{item.1.index | default(item.0)}}"
    device: "{{item.1.device}}"
    vlan: "{{item.1.vlan}}"
    vid: "{{item.1.vid}}"
    ports: "{{item.1.ports | default([]) | join(' ')}}"
  with_indexed_items: "{{switch_vlans}}"
