---
- name: set ifname
  uci:
    command: set
    config: "network"
    section: "{{name}}"
    type: "interface"
    option: "ifname"
    value: "{{ifname}}"
  when: ifname != ''
  notify:
    - uci commit network
    - reload network for openwrt-network

- name: set ipaddr
  uci:
    command: set
    config: "network"
    section: "{{name}}"
    type: "interface"
    option: "ipaddr"
    value: "{{ipaddr}}"
  when: ipaddr != ''
  notify:
    - uci commit network
    - reload network for openwrt-network

- name: set netmask
  uci:
    command: set
    config: "network"
    section: "{{name}}"
    type: "interface"
    option: "netmask"
    value: "{{netmask}}"
  when: netmask != ''
  notify:
    - uci commit network
    - reload network for openwrt-network

- name: set username
  uci:
    command: set
    config: "network"
    section: "{{name}}"
    type: "interface"
    option: "username"
    value: "{{username}}"
  when: username != ''
  notify:
    - uci commit network
    - reload network for openwrt-network

- name: set password
  uci:
    command: set
    config: "network"
    section: "{{name}}"
    type: "interface"
    option: "password"
    value: "{{password}}"
  when: password != ''
  notify:
    - uci commit network
    - reload network for openwrt-network

- name: set proto
  uci:
    command: set
    config: "network"
    section: "{{name}}"
    type: "interface"
    option: "proto"
    value: "{{proto}}"
  when: proto != ''
  notify:
    - uci commit network
    - reload network for openwrt-network

- name: set type
  uci:
    command: set
    config: "network"
    section: "{{name}}"
    type: "interface"
    option: "type"
    value: "{{type}}"
  when: type != ''
  notify:
    - uci commit network
    - reload network for openwrt-network

- name: set auto
  uci:
    command: set
    config: "network"
    section: "{{name}}"
    type: "interface"
    option: "auto"
    value: "{{auto | int}}"
  when: auto != ''
  notify:
    - uci commit network
    - reload network for openwrt-network
