---
- name: set switch_vlan device
  uci:
    command: set
    config: "network"
    index: "{{index}}"
    type: "switch_vlan"
    option: "device"
    value: "{{device}}"
  notify:
    - uci commit network
    - reload network for openwrt-network

- name: set switch_vlan vlan
  uci:
    command: set
    config: "network"
    index: "{{index}}"
    type: "switch_vlan"
    option: "vlan"
    value: "{{vlan}}"
  notify:
    - uci commit network
    - reload network for openwrt-network

- name: set switch_vlan vid
  uci:
    command: set
    config: "network"
    index: "{{index}}"
    type: "switch_vlan"
    option: "vid"
    value: "{{vid}}"
  notify:
    - uci commit network
    - reload network for openwrt-network

- name: set switch_vlan ports
  uci:
    command: set
    config: "network"
    index: "{{index}}"
    type: "switch_vlan"
    option: "ports"
    value: "{{ports}}"
  notify:
    - uci commit network
    - reload network for openwrt-network
